options:
  logging: CLOUD_LOGGING_ONLY
  # logStreamingOption: STREAM_ON
  # logsBucket: 'logging_bucket_cicd' 

steps:
  # Step 1: Install dependencies and run tests
  - name: 'python:3.8'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt 
        

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/adept-mountain-416817/my-fastapi-app:$COMMIT_SHA', '.']

  # Step 3: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/adept-mountain-416817/my-fastapi-app:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-fastapi-service'
      - '--image=gcr.io/$PROJECT_ID/my-fastapi-app:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      # - '--set-env-vars=PORT=8080'

# Images to be stored in the Container Registry
images:
  - 'gcr.io/adept-mountain-416817/my-fastapi-app:$COMMIT_SHA'

# Set substitutions for variable values
substitutions:
  _REGION: 'us-central1'
