name: CI/CD Pipeline to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  setup-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup GCP Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.0'
          service_account_key: ${{ secrets.dbd354b850caf74ce5a6a751eb74c70d89f3df9e }}
          project_id: ${{ secrets.adept-mountain-416817 }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.adept-mountain-416817 }}/fastapi-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy fastapi-app --image gcr.io/${{ secrets.adept-mountain-416817 }}/fastapi-app:$GITHUB_SHA --platform managed --region your-region --allow-unauthenticated
